import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AuthProvider } from './context/AuthContext';
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Toaster position="top-center" />
          <div className="flex h-screen flex-col items-center">
            <main className="mt-auto mb-auto flex min-w-xs">{children}</main>
            <footer className="mb-4 text-sm">
              built by{' '}
              <a href="https://vzkiss.com" className="underline">
                vzkiss
              </a>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
